### ISSUE TITLE
Please update to latest pact (1.10.0 right now)

### ISSUE THREAD

**Issue by SchulteDev** [DiUS/pact-provider-verifier-docker#1]
Hi there,

this very helpful docker-image seems to be using pact1.9.0.
For time being most recent version is 1.10.0 https://rubygems.org/gems/pact For the actual changes, you can have a look at https://github.com/realestate-com-au/pact/blob/master/CHANGELOG.md

Please update.

**Comment by mefellows** [comment]
My apologies, I did not see this issue!

(I'll update my Slack integration to include this repo).

Thanks for the PRs, I will review in the new few days - seems completely sensible and love that you've got this working with Alpine!

**Comment by mefellows** [comment]
This is a test comment to see if it appears in the #pact channel.

**Comment by SchulteDev** [comment]
Nothing to apology :-)

**Comment by bethesque** [comment]
This has got a very recent version now, closing.
